### PR TITLE
Drop deprecated (already deprecated)

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by jankal** [comment]
When we drop support here, we need to also drop support on the themes.

**Comment by fschlich** [comment]
I think deprecated is a useful feature, both for people working on code that uses your library to update before it stops working, as well as for the library devs themselves to remember to get back to removing deprecated features after good while.

Please don't remove unless it's actually a burden to maintain!

**Comment by TomasVotruba** [comment]
This feature is covered by annotation-group

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
