### PR TITLE
dropping php internal

### PR DESCRIPTION
**Pull request by TomasVotruba**
This PR is to get feedback and think about it.

I'm thinking, that the main aim of this project is to document PHP project, rather then documment PHP API itself. The original [PHP.net](http://php.net/) does quite good work itself.

Also looking at Nette, Doctrine, CakePHP, Kdyby and Amazon, nobody uses this.

Saying that, possibly drop internal PHP classes management:

- [ ] drop generator for internal PHP

### CODE REVIEW

**Comment by POPSuL** [comment]
Why?

**Comment by TomasVotruba** [comment]
Could you elaborate?

**Comment by jankal** [comment]
@POPSuL is put on hold until arguments are done.

I personally see this as a very good thing for dropping maintainance time cost while we are bumping to 7.1

**Comment by TomasVotruba** [comment]
Ping @POPSuL

**Comment by TomasVotruba** [comment]
For me, this is ready to merge.

**Comment by jankal** [comment]
Yes okay. We need to make progress here. I'll merge.

**Comment by TomasVotruba** [comment]
Thank you.

I'm gonna rebase my master and resend changes from opened PRs in smaller PRs.

**Comment by jankal** [comment]
@TomasVotruba Okay. Just don't `push -f` as I did on sunday ;)

**Comment by TomasVotruba** [comment]
@jankal Okay ;)

**Pull request merged**
