### PR TITLE
Theme: fixed whitespace wrapping for long description

### PR DESCRIPTION
**Pull request by vlastavesely**
## Before
before

## After
after

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the fix. Have you tested that on mobile? It think it might be related.

It would also make sense to make "public" column much shorted. (Bad idea: maybe using `col-md-1`?)

**Comment by vlastavesely** [comment]
On mobile? No,I just resized browser window and after my fix it looks good.

But I've found another problem :) In the older ApiGen, there was return typehint in the first column:

hint

It needs to be fixed also :) I will do that tomorrow and then we can shorten the first column if needed.

**Comment by TomasVotruba** [comment]
Allright :). Thanks for your weekend time on this. Much appreciated :+1:

**Comment by vlastavesely** [comment]
Could you merge it as it is - without the return types? For new changes I need the changes we already merged after I started working on this. I would start with new PR.

After the changes from this PR, it looks like this:
screenshot-1

**Comment by TomasVotruba** [comment]
Right align was removed for bad readability in case of extra values, see: https://github.com/ApiGen/ApiGen/pull/925#issuecomment-312515770

I'd suggest going for `<td class="col-md-1">` for 1st column and `<nobr>` for it's content. It might look very nice without any extra css.

Could you try that?

**Comment by vlastavesely** [comment]
Two examples of current state. First one is on small screen, second one on a wide screen.
screenshot-1

**Comment by TomasVotruba** [comment]
Looks good to me. Can i Merge it?

**Comment by vlastavesely** [comment]
yes.

**Comment by TomasVotruba** [comment]
Done! Thansk

**Pull request merged**
