### PR TITLE
[ThemeDefault] add to local package + coding standard extension

### PR DESCRIPTION
**Pull request by TomasVotruba**
Put code https://github.com/ApiGen/ThemeDefault back to repository to make upgrade and testing easier

Ref:

- https://www.tomasvotruba.cz/blog/2017/01/31/how-monolithic-repository-in-open-source-saved-my-laziness/
- https://www.tomasvotruba.cz/blog/2017/02/07/how-to-decouple-monolith-like-a-boss-with-composer-local-packages/

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ready to merge

**Comment by jankal** [comment]
Merged for now. But I didn't find any composer.json inside the package as you mentioned in your blog post. 

There also was no linking done trough the master composer.json file - `repository: packages...`

**Comment by TomasVotruba** [comment]
Thank you!

As for local package linking, it is only possible for your main application repository. Not for packages.

See here: https://github.com/composer/composer/issues/6253

**Comment by jankal** [comment]
Oh okay. But why don#t we have a `composer.json` inside the package dir? - Like Laravel does for `Illuminate`?

**Comment by TomasVotruba** [comment]
This is not monorepo to be split. No need for it, because this is one project that needs all it's components.

It's not like Laravel who has 20+ components to be used standalone.

**Comment by jankal** [comment]
Okay. Now I understand.

**Comment by jankal** [comment]
Thanks for explaining. @TomasVotruba 

Keep up the great work!

**Comment by TomasVotruba** [comment]
Thank you :1st_place_medal:

**Pull request merged**
