### PR TITLE
Better-Reflection dev-master#c87d856 is no more working #1046

### PR DESCRIPTION
**Pull request by dimabory**

### CODE REVIEW

**Comment by vipinjn24** [comment]
`"roave/better-reflection": "dev-master"` works please update accordingly.

**Comment by dimabory** [comment]
@vipinjn24 sure, but the next commit can break something again

**Comment by Saibamen** [comment]
status?

**Comment by giansalex** [comment]
Someone can merge?

**Comment by JanTvrdik** [comment]
No longer relevant since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha

**Pull request closed without merging**
