### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by marcovtwout**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Great! Thank you.

Just detail, could you turn --debug into `--debug`, so it's clear it's code?

**Comment by TomasVotruba** [comment]
Could you repush/squash to 1 commit?

**Comment by marcovtwout** [comment]
I made this change through the GitHub interface instead of clone/fork, so this would take relatively a lot of work for such a simple change. Is the benefit worth the trouble?

**Comment by TomasVotruba** [comment]
I'd like to keep simple history for others, but if it's too complicated for you, I'm fine with it.

Thanks for your work'

**Pull request merged**
