### PR TITLE
Bump to PHP 7.1

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@coveralls Don't spam here!

Can anyone turn this off?

**Comment by TomasVotruba** [comment]
Tests are passing :heavy_check_mark:

**Comment by jankal** [comment]
This is verbose. If #788 is merged, we won't need this anymore cause it's included in #788

**Comment by TomasVotruba** [comment]
What do you mean by "verbose"?

Yep, that includes this PR. It waits on this PR to be merged.

**Comment by jankal** [comment]
OK. Just forget it. I was just thinking about having them independant like creating another branch for each PR may be better.

**Comment by TomasVotruba** [comment]
Yea, that would be better. But I thought this would be already merged.

**Pull request merged**
