### PR TITLE
Loader uses @include instead of require

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
New stable 4.0 is here, so 2.8 is not officially supported anymore.

**Comment by dg** [comment]
Why you didn't merge it?

**Comment by GrahamCampbell** [comment]
Because 2.8 is not supported anymore.

**Comment by dg** [comment]
This commit is here for two months…

**Comment by GrahamCampbell** [comment]
I assume it required review by @kukulich, and there was no response, so then this pull request remained open beyond the time period where 2.8 was maintained, so is now closed.

**Comment by dg** [comment]
I understand, but obvious things can be fixed without review by one of authors.

**Comment by TomasVotruba** [comment]
As @GrahamCampbell said, @kukulich didn't merge it in last 2 months. I was waiting till stable release with this.

I take responsibility only for v4+ since I don't understand all consequences in v2.8.

**Pull request closed without merging**
