### PR TITLE
Support for array-notation typehint for @property and @method

### LINKED ISSUE #696: need to support [] in var type notation
example:

     * @property Poi\Alias[] $alias Alias List

It doesn't work now, but it can work in ide (NetBeans etc.)

### PR DESCRIPTION
**Pull request by POPSuL**
This PR fixes #696

### CODE REVIEW

**Comment by POPSuL** [comment]
Oups. I probably broke tests and something else... I will fix it later.

**Comment by jadb** [comment]
Thanks!

**Comment by POPSuL** [comment]
Just close? :(

**Comment by jadb** [comment]
HUH?

**Comment by jadb** [comment]
Sorry :( 

Clicked the wrong button!

**Pull request merged**
