### PR TITLE
Drop tree

### PR DESCRIPTION
**Pull request by TomasVotruba**
This is rather nice-to-see once feature than useful one. I never really used and it just show all classes. I think **it's same use as showing all posts on blog**. I look for particular class and it's relations, not to see it all.

### CODE REVIEW

**Comment by jankal** [comment]
Have no opinion on that myself.

Do @kukulich @POPSuL @ek9 have any opinions about this?

**Comment by POPSuL** [comment]
I did not even know about this and did not use this thing.
If this is the same as the one in the left pane (separate page with tree of namespaceses with classes) - it is not necessary IMHO.
If I'm wrong - show a screenshot of what you mean. I currently can't see what this option does :(

**Comment by jankal** [comment]
@POPSuL I think you meant the same thing as I also meant ;).

So this is ACCEPTED and will be MERGED.

**Comment by TomasVotruba** [comment]
@POPSuL Same for me. Yep it's pretty similar to the structure in the left :) 

Thank you guys.

**Pull request merged**
