### PR TITLE
Phar drop

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by dans98** [comment]
Tomas, does this mean ApiGen will no longer be distributed as a phar?

**Comment by TomasVotruba** [comment]
Yes. I do not have capacity to develop this project and provide support in range as it is anymore.
Rather then abandon it completely, I've decided to decrease number of features. Those I do not consider the most useful. This is very difficult and new situation to me, still I'll try to explain myself.

To be specific: it is nice to have PHAR, but when the the generation process fails on [PHP 5.6 project](https://github.com/ApiGen/ApiGen/labels/PHP%205.6), there is something wrong. Now I see I would rather do not deal (add feature, maintain it, fix bugs, release new one on every tagged version etc.) with PHAR at all and rather provide support for PHP 5.6.

I need to find joy a meaning in project and I do not find it any ApiGen anymore. I took it over about a year ago after 2 years of deprecation, with no tests, great technical dept and few difficult bugs. It's not my project, not my passion, nor my field of expertise.

Personally I prefer IDE or Github to find what I need, or rather read documentation of the project. 

I might be wrong about this decision, but I don't see any other way how to keep this project alive in near future. 

How would you (all) approach this situation yourself?

**Comment by TomasVotruba** [comment]
https://twitter.com/VotrubaT/status/605132675347820544

**Comment by g0morra** [comment]
Hi Tomas, I just wanted to say thanks for your work on Apigen.

Recently I re-architected my core framework that I use to earn a living.  One requirement was generating uniform api docs for both my own framework and all its third party dependencies, so I could just code against the api docs without having to touch the source.  Apigen was *definitely* the best tool for the job out of the current range of php doc projects.  It was relatively easy to get the output and the template how I wanted.  Other projects could have done the job, but getting them to work how I wanted was going to be a nightmare.  I found Apigen has a sensible default structure for the generated docs and most importantly I could quickly grok how to modify the excellent bootstrap template and get the output exactly how I wanted it, even though I had never touched Nette before.  Now I have useful, usable, attractive and generally awesome api docs that I work from every day.

I'm not qualified to take over maintaining the project, but I find the source is clean and easy to work with so I'll continue to fiddle with it.  I just wanted to show my appreciation because using Apigen to generate good personal api docs has made a massive difference to my productivity and work life.  Thanks again!

**Comment by TomasVotruba** [comment]
Hey @g0morra ,

thanks a lot for these nice words of appreciation. I'm really touched and pleased you find this project useful. Easy to run and the code clean to modify - that's all I ever wanted.

I don't know what to say more, but I will definitely read it once more. It really cheers me up!

**Comment by TomasVotruba** [comment]
Hey @g0morra ,

thanks a lot for these nice words of appreciation. I'm really touched and pleased you find this project useful. Easy to run and the code clean to modify - that's all I ever wanted.

I don't know what to say more, but I will definitely read it once more. It really cheers me up!

**Comment by stevleibelt** [comment]
Hi @TomasVotruba, 

Thank you very much for the time you spend on this project. You did an incredible work.
Maintaining such a big code base alone is not doable in spare time. I could not write as many words as @g0morra did, but the thank you bumping from my heart is as big as his - hopefully.

 Peace, and stay with the force :-).

**Comment by TomasVotruba** [comment]
@stevleibelt Thank you Steve, this really means a lot to me.

**Comment by stevleibelt** [comment]
@TomasVotruba 
I am a bit sad that there are not more posts. I'n my world, apigen was the defacto standard :-).
I owe you some beers/drinks/mate whenever you are in Hamburg.

**Comment by TomasVotruba** [comment]
@stevleibelt I'm ok with that, I wasn't making ApiGen to get celebrated. I did it because I enjoyed it and learned a lot. It also got me to Symfony, which is priceless experience.

Haha, I'd love to drink with you :). Actually, I'm at #ipc15 in Berlin ATM, that's the closest I can get.

**Comment by stevleibelt** [comment]
Well, would be really cool but I'm far away at that time :-(.

**Comment by TomasVotruba** [comment]
@stevleibelt That's ok. Enjoy the rest of the week!

**Comment by olvlvl** [comment]
Thanks @TomasVotruba for the excellent work you did on ApiGen. I'll be glad to maintain the [bootstrap theme](https://github.com/ApiGen/ThemeBootstrap)… after all I created it :) Take care ++

**Comment by TomasVotruba** [comment]
@olvlvl Wow, thanks a lot! These few words of yours made me really happy :).

**Comment by taylorren** [comment]
@TomasVotruba 

It is really sorry to see the sad news about the future development of the `apigen` PHAR. I was trying to write something on it in Sitepoint to promote this cool tool. 

I wrote a few self-use PHP sites and now I am re-factoring everything. During this process, I need a proper documentor so that I can keep myself (and interested users) clearer about what I am going to structure, provide. 

Tried a few other tools, but `apigen` stands out for its "just nice" feature (well, not the complete feature). 

Thanks.

**Comment by half2me** [comment]
@TomasVotruba A big thanks from me for this awesome project. I use CakePHP for almost all of my projects, and I use their API generated by ApiGen all the time, when I don't understand something from the docs. I think such an API documentation is a must-have for frameworks.

Right now I'm working on a private project, and I had to build an API for other developers to use. I used to document it by hand, copy pasting etc. ApiGen has made my life so much easier. I owe a lot to this project...

**Comment by TomasVotruba** [comment]
@half2me Thank you for your nice words. I'm really happy I brought such a light to your programming life just with a year of maintenance. You made my weekend much better :)

**Comment by jankal** [comment]
@TomasVotruba are you having some fun again with this?

**Comment by TomasVotruba** [comment]
@jankal Thanks for asking. Indeed I am :) 

Having almost 2 years of experience with open-source, it's great to see my own mistakes on one hand, and great decisions that lasts on the other hand.

Having 90 %+ coverage makes everything much easier. I'm so glad I put time into that.

**Pull request merged**
