### PR TITLE
fixed TreeGenerator, now really generates trees

### PR DESCRIPTION
**Pull request by dg**
Currently it generates flat structure.

### CODE REVIEW

**Comment by jadb** [comment]
Tests are failing here :cry:

**Comment by dg** [comment]
I'll check it

**Comment by dg** [comment]
@jadb tests fixed.

Also fixed test fail introduced in https://github.com/ApiGen/ApiGen/pull/705

**Comment by dg** [comment]
Btw, there is already cca 10 tests that fails on Windows because of different directory separator

**Comment by dg** [comment]
Hmmm, there is still one failing test in some environment `ApiGen\Tests\Generator\TemplateGenerators\TreeGeneratorTest::testCanBeProcessed
Failed asserting that true is false.` but I have absolutely no idea what is does and how to fix it. I am throwing in the towel.

**Pull request closed without merging**
