### PR TITLE
Parser: Adds unit tests for PHP 5.6 features

### PR DESCRIPTION
**Pull request by sophie-h**
This unit tests should cover all relevant PHP 5.6 features. 2/3 are currently failing. The pullrequest is in response to https://github.com/apigen/apigen/issues/494, https://github.com/apigen/apigen/issues/495

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks. First I need to update https://github.com/apigen/TokenReflection library, WIP

**Comment by ek9** [comment]
I've merged the contents of it to `php5.6` branch (it's based on `master`).

**Comment by TomasVotruba** [comment]
Ok

**Comment by ek9** [comment]
I was tihnking of merging them to master (but perhaps marking them incomplete?). This way they would not cause problems for pull requests and would be marked as incomplete / show a warning. What do you think?

**Pull request merged**
