### PR TITLE
Support for PSR-2

### PR DESCRIPTION
**Pull request by POPSuL**
- [x] Added .styleci.yml
- [x] Fixed all php-cs-fixed warnings
- [ ] Owner of this repo (@jadb?) shall register on https://styleci.io, enable ApiGen/ApiGen for analysis and add the badge into readme.

### CODE REVIEW

**Comment by jankal** [comment]
@TomasVotruba This would be next on the list.

**Comment by TomasVotruba** [comment]
@jankal Yep. I will handle this.

With [EasyCodingStandard](https://github.com/Symplify/Symplify/blob/master/packages/EasyCodingStandard/README.md#start-slow-grow-fast) - WIP for a few more days.

**Comment by jankal** [comment]
Fine.

**Comment by TomasVotruba** [comment]
@jankal Offtopic: Ha, I see you are from Munich. I was just there week ago for first time!

**Comment by jankal** [comment]
@TomasVotruba Is there any chat where we could speak off-topic? Telegram?

**Comment by TomasVotruba** [comment]
@jankal I PMed you on mail

**Comment by jankal** [comment]
I just signed this up to styleci.

**Comment by jankal** [comment]
Am not able to enable styleci. It requires admin rights. @kukulich Will you sign up and enable it?

**Comment by kukulich** [comment]
I don't see any benefits for styleci, Travis should be enough I think.

However If @TomasVotruba and @jankal would want styleci, I will do the registration.

**Comment by jankal** [comment]
@TomasVotruba do you? I don't really know cause we now have the phpstan in Travis. Just commented on that to follow the PRs list.

**Comment by jankal** [comment]
Ping @TomasVotruba

**Comment by TomasVotruba** [comment]
Travis just fine. StyleCI is limited service for those, who do not use codings standards on daily basis.

**Comment by jankal** [comment]
Okay. So can we close this? @TomasVotruba?

**Comment by TomasVotruba** [comment]
Yes. It will be replaced by #811, with more precise setup.

**Pull request closed without merging**
