### PR TITLE
add cache to avoid recurring reflection of classes

### PR DESCRIPTION
**Pull request by jenschude**
I identified one of the bottlenecks in the parsing to be the parentClass resolver. As the reflected classes are not modified it should be possible to introduce a cache of reflected classes which speeds up the parsing a lot.

### CODE REVIEW

**Comment by jenschude** [comment]
For comparison I ran ApiGen once on the src folder

actual master:
```
time bin/apigen generate src --destination docs
Parsing reflections (this may take a while)... done!
Generating documentation...
 152/152 [============================] 100% 4 mins/4 mins 326.0 MiB. done!
Your documentation has been generated successfully!
bin/apigen generate src --destination docs  277.67s user 10.80s system 99% cpu 4:48.91 total
```

PR-branch:
```
time bin/apigen generate src --destination docs2
Parsing reflections (this may take a while)... done!
Generating documentation...
 152/152 [============================] 100% 3 secs/3 secs 22.0 MiB. done!
Your documentation has been generated successfully!
bin/apigen generate src --destination docs2  4.03s user 0.14s system 99% cpu 4.186 total
```

**Comment by jankal** [comment]
This looks ready for merge.
Have to check back with current master (re-run test on base of current master).

**Comment by POPSuL** [comment]
Why not merged yet?

**Comment by JanTvrdik** [comment]
No longer relevant since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha

**Pull request closed without merging**
