### PR TITLE
Add support for v3 version of Symfony Components

### PR DESCRIPTION
**Pull request by ek9**
Add support for v3 version of Symfony Components. Update the test so it can be run with v2 and v3 version of `symfony/console`

### CODE REVIEW

**Comment by ek9** [comment]
This fixes #770 

Please let me know if there is something I might have missed, but all the tests run fine in both versions of `symfony/console`. Otherwise, I did not have to update anything else. Unless there are things not convered by tests, this should be safe to merge.

**Comment by ek9** [comment]
ping @jadb @POPSuL , could we merge this in for Symfony3 support?

**Comment by ek9** [comment]
Any comments or status on the PR? :)

**Comment by jankal** [comment]
Close and reopen for CI run again.

**Comment by jankal** [comment]
My be closed in favor of #789

**Comment by ek9** [comment]
Just a quick ping to @jankal, my fix had support for both symofny 2.8 and 3.0 series. The older 4.1.* version have problems which require you to use master for symfony 2.8 LTS. I believe the 4.2 series should support both (2.8 and 3.0), especially that now PHAR support is dropped and there is no way to use `apigen` without it dictating the versions of components to use. I would suggest to go symfony 3.0 only on 4.3 in the future.

**Comment by jankal** [comment]
@TomasVotruba ping

**Comment by ek9** [comment]
Perhaps it would be more appropriate to discuss this on https://github.com/ApiGen/ApiGen/issues/770 issue. I've made separate comment there + explained the use case.

**Comment by TomasVotruba** [comment]
There have been many BC breaks, to revive the project.
I'm here to focus on 5.0 release. I don't have time to handle anything more.

**Pull request closed without merging**
