### PR TITLE
Deprecated generators

### PR DESCRIPTION
**Pull request by TomasVotruba**
Didn't bring much value to generated docs

### CODE REVIEW

**Comment by fprochazka** [comment]
Why? I liked the sitemap :-/

**Comment by TomasVotruba** [comment]
It's not so relevant to the docs. Also still to big to maintain for me.

I moving toward plugins like composer has, to allow add custom generators, if you really need it.

**Comment by fprochazka** [comment]
Well, I just fail see the benefit of removing something that is working...

**Comment by TomasVotruba** [comment]
Also it's not suitable for these kinds of projects, quoting [Google Docs](https://support.google.com/webmasters/answer/156184?hl=en).

> Well, I just fail see the benefit of removing something that is working...

Development process is not in "working" state yet. I'd really appreciate bugfixes to make closer to that state.

**Pull request merged**
