### PR TITLE
Implemented fuzzy search

### PR DESCRIPTION
**Pull request by POPSuL**
Related issue: https://github.com/ApiGen/ApiGen/issues/881
Examples:
image
image
image

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for submitted PR.

Does it support highlighting of searched text?

Can I pick up solution by mouse and keyboard?

**Comment by TomasVotruba** [comment]
See #932 for other solution.

I like it's simplicity and text-highlighting, even if doesn't fuzzy search items.

**Comment by POPSuL** [comment]
@TomasVotruba highlighting is not implemented yet.
Items can be picked both keyboard (type some text -> down/up -> enter) and mouse (just click)

**Comment by POPSuL** [comment]
@TomasVotruba I don't mind this (#932) decision if it implements a fuzzy search :)

**Comment by TomasVotruba** [comment]
Ok, let's continue there then :+1: 
We can take it gradually

Thanks for your openness

**Pull request closed without merging**
