### PR TITLE
updated test [failing]

### PR DESCRIPTION
**Pull request by vlastavesely**
`ClassMethodReflection::getDefaultValueDefinition()` can return mixed types but typehint is only for string. The same goes for `TraitMethodReflection::getDefaultValueDefinition()`.

Some variable dumper must be added or real definition loaded in some way.

Any tips how to solve it?

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for propper test case.

I think that solution is to convert this to plain string and return it
E.g. 

```php
public $arrayProperty = ['cat', 'dog'];
```

return:

```
" = ['cat', 'dog'];"
```

Probably using some function like [`htmlspecialchars`](http://php.net/manual/en/function.htmlspecialchars.php). Not sure exactly which now.

**Comment by vlastavesely** [comment]
> I think that solution is to convert this to plain string and return it.

Oh yes, it is. But there are two possible solutions. One is to extract somehow the `" = ['cat', 'dog'];"` string from file directly or use output of `betterPropertyReflection->getDefaultValue()` and pas it into some dumper like `Nette\PhpGenerator\Helpers::dump()` or `var_export()`. I am not sure what would be better.

**Comment by TomasVotruba** [comment]
First one would be better to comply with currenct ApiGen architecture. I'm not sure how much work that is.
Feel free to pick one that suits you best and is easy to add.

**Comment by vlastavesely** [comment]
I've looked on that and first solution does not seem to be easy. Probably, I try the second one. It can be changed later.

**Comment by TomasVotruba** [comment]
I've rebased the PR on `master`, as there were some conflicts.

**Comment by vlastavesely** [comment]
Fixed. In the future, the better dumper can be used but right now, we need it working in any way.

Now it looks like this:
screenshot

**Comment by TomasVotruba** [comment]
I like it, pretty neat solution! :+1: 

Thanks for the screenshots, it saves me lot of time running tests and generating own output.

**Pull request merged**
