### PR TITLE
[WIP] [BetterReflection] use DI approach

### PR DESCRIPTION
**Pull request by TomasVotruba**
Follow up to:

- https://github.com/Roave/BetterReflection/pull/338
- #987
- #951

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Expected speed-up went a bit wrong. From few seconds per test to 2 minutes.

Not sure what I'm doing wrong.

https://blackfire.io/profiles/5e1fa282-64ef-4e56-9b0c-1534b4622467/graph

**Comment by TomasVotruba** [comment]
Ha, getting somewhere now...

**Comment by TomasVotruba** [comment]
@vlastavasely Could you help me with this please?

There are 3 tests failing. Probably because of exception/throwable issue.

1. StepCounter - 1 is missing: https://travis-ci.org/ApiGen/ApiGen/builds/271692658#L716

2. Here it switched from `interface-Throwable` to `class-Exception`: https://travis-ci.org/ApiGen/ApiGen/builds/271692658#L727
Maybe correct, not sure.

3. Here - `SomeFunction` is not found.
https://travis-ci.org/ApiGen/ApiGen/builds/271692658#L734

**Comment by vlastavesely** [comment]
OK, I will check it during a day.

**Comment by TomasVotruba** [comment]
I won't have time for this PR, because I will focus my open-source full time on @RectorPHP  
Moreover to check news in BetterReflection 2.0 at the moment.

Feel free to taky anything useful from it though.

**Pull request closed without merging**
