### PR TITLE
added highlighting of method's param default value

### PR DESCRIPTION
**Pull request by vlastavesely**
screenshot-3

:question:  any reason why default color of the `code` is reddish in color? It is unintended leak from the Bootstrap?

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the PR! I'm curious. How did it look before? :)

> :question: any reason why default color of the code is reddish in color? It is unintended leak from the Bootstrap?

Probably. Which one is "normal"?

Also, could you keep "…" or did that cause any troubles? It's more readable and nowadays UTF-8 is supported by default.

**Comment by vlastavesely** [comment]
> How did it look before? :)

All was reddish without bold. Do you need a screenshot? :camera_flash:  

>  Which one is "normal"?

Normal would be black and the reddish color could be used only when special class is added to `code` - for example for the `public`, `static` keywords etc. But not in the list of parameters - there it looks quite strange. Do you agree?

**Comment by vlastavesely** [comment]
old

It looked like this - this is a screenshot from older PR.

**Comment by TomasVotruba** [comment]
Yea, it makes sense. I agree! 🌳 

Thanks for screen, I understand now.

**Comment by vlastavesely** [comment]
screenshot-4

Looks much better now! But I am not sure with the class name - there can be even another things than keywords. Any tip for better name?

**Comment by TomasVotruba** [comment]
I'm fine with "keyword", makes sense

**Comment by vlastavesely** [comment]
> I'm fine with "keyword", makes sense

:+1:

**Pull request merged**
