### PR TITLE
tests: added class extending from another project

### PR DESCRIPTION
**Pull request by vlastavesely**
Test for #912

But from `phpunit`it ends with FATAL ERROR instead of exception. It confuses me a little - is it right or have I miss something...?

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I think `BetterReflection` requires the class to be loaded by design.

I'm not sure it would solved your issue, but could your add the parent class to another directory (not the ApiGen generates it from)? So we see, if the class can be autoloaded.

---

As for different vendor issue, do you have any idea for solution?

I think we can use [`ComposerSourceLoader`](https://github.com/Roave/BetterReflection/blob/master/src/SourceLocator/Type/ComposerSourceLocator.php#L17) to [our Parser](https://github.com/ApiGen/ApiGen/blob/b13e5bc7b59c7af4b13f34e0dea76bf0b68377c2/packages/Reflection/src/Parser/Parser.php#L120), but we'd need to pass location to the `vendor/autoload.php` to apigen command.

Something like:

```
bin/apigen generate --preferred-vendor-autoload other-vendor/autoload.php
```

**Comment by vlastavesely** [comment]
> could your add the parent class to another directory

How do you mean it?
In `repo/src`, I have source files and in `repo/vendor` installed all dependencies. But if I pass `repo/src` to ApiGen, it should ignore all other directories.


Maybe we could assume as default path to autoload path `../vendor` from the directory that is specified for `generate` command...?

But what if I need to generate source from two such repositories at once and with same dependencies...?

**Comment by TomasVotruba** [comment]
> How do you mean it?

I talk about this test:

- create `SomeNamespace\ParentClass` from the test 
- add it to `tests/Generator/NotLoadedSources/ParentClass.php`
- rename it to match PSR-4:  `ApiGen\Tests\Generator\NotLoadedSources\ParentClass`

--

> Maybe we could assume as default path to autoload path ../vendor from the directory that is specified for generate command...?

Yea, that might be much easier :+1: 

That would require only adding `ComposerSourceLocator` with `getcwd() . '/vendor/autoload.php'` as argument. If file would exists.

Could you try that?

**Comment by vlastavesely** [comment]
This is seems to be working.

Yes, I could.

**Comment by TomasVotruba** [comment]
> This is seems to be working.

Thanks, I'll merge it, so we have this covered.

> Yes, I could.

Thanks. If you came up with `.travis.yml` setup which would test it, we could cover that too.

**Comment by vlastavesely** [comment]
You have merget it already? I have pushed the change just now....

**Comment by vlastavesely** [comment]
It worked for the test case we have. But the `ComposerSourceLocator` was not already done.

**Comment by TomasVotruba** [comment]
Oh, I thought you'd create a new branch. I'm sorry.

Could you resend PR?

**Pull request merged**
