### PR TITLE
Use any theme defined in vendor

### PR DESCRIPTION
**Pull request by olvlvl**
This PR allows using any theme defined in `vendor/apigen/`.

### CODE REVIEW

**Comment by jankal** [comment]
@TomasVotruba Able to merge?

**Comment by TomasVotruba** [comment]
@jankal Not sure. I'm not much in templating.

**Comment by jankal** [comment]
@TomasVotruba I'll read trough it.

**Comment by jankal** [comment]
Close and reopen for CI to run again.

**Comment by jankal** [comment]
To me looks mergable.

**Pull request merged**
