### PR TITLE
Drop phar

### PR DESCRIPTION
**Pull request by TomasVotruba**
## Why?

This requires too much work and causes too many issues - see those 10 bellow.
Rather than playing with this, we should focus on reflection and PHP 7+ features.

Depends on: #787 

Resolves: 

- #780
- #773
- #761
- #760
- #733
- #732
- #675
- #638
- #775

### Dependencies Cleanup

image

### CODE REVIEW

**Comment by jankal** [comment]
Nice.  @TomasVotruba Thanks for removeing PHAR support. This will make deployment a lot easier (almost no deployment...).

**Comment by TomasVotruba** [comment]
I've noticed PHPUnit too late. What this is not merged?
To bad.

Yep, it should bring more peace in here :) I know I spent weeks on it here.

**Comment by jankal** [comment]
Nah. I think it's good enough like this.

May I merge your version?

**Comment by TomasVotruba** [comment]
Awesome!

**Comment by TomasVotruba** [comment]
Could you also close those issues that I mentioned?

**Comment by jankal** [comment]
Yep I will.

**Pull request merged**
