### PR TITLE
Cleanup - ready to merge

### PR DESCRIPTION
**Pull request by TomasVotruba**
- drop file licenses, not really needed
- drop phar from gitignore
- scrutinizer cleanup
- travis cleanup
- phpstan added
- drop coverrals (spam), use scrutinizer

### CODE REVIEW

**Comment by jankal** [comment]
For removing license, we first need to ask if @kukulich allows that. It's his code.

**Comment by TomasVotruba** [comment]
@jankal Sure.

**Comment by jankal** [comment]
You just recreated #769

**Comment by TomasVotruba** [comment]
@jankal Yes, please. Thank you

**Comment by TomasVotruba** [comment]
I actually cleaned this. Coverrals is not needed. It give so much spam  :(

**Comment by jankal** [comment]
Oops just overwritten your last change by a `geit push -f` cause I needed to change the commits name.

@TomasVotruba

**Comment by TomasVotruba** [comment]
@jankal Rather open new PR. It goes bad when 2 commits to one branch on live :D

**Comment by jankal** [comment]
I'm on it.

**Comment by jankal** [comment]
I'm not able to disable coveralls. @kukulich needs to do that. Don't have admin permission to that repo.

**Comment by jankal** [comment]
May @TomasVotruba you just do my commit of changing to `vendor/bin/phpunit`?

**Comment by TomasVotruba** [comment]
@jankal  Ok, thanks for checking. We'll have to tolerate it until then.

The phpunit multi-call has been removed: https://github.com/ApiGen/ApiGen/pull/789/commits/3af9effb6c231c939adfa60441de7e8b553d2ec6

**Comment by jankal** [comment]
Nah... don't you...
I'd like it to stay active. Cause you actually can disabe the comment-spam without disabling the whole coveralls.

**Comment by TomasVotruba** [comment]
@jankal Scrutinizer does the same, without spam by default.

**Comment by jankal** [comment]
Then you may revert #785

**Comment by jankal** [comment]
That was when I replaced Scrutinizer with Coveralls.

**Comment by jankal** [comment]
Don't tests with Scrutinizer run twice? Once on Scrutinizer and once on Travis?

**Comment by TomasVotruba** [comment]
@jankal That's already in.

I just add PHPStan and I'm over.
To bad I didn't add more deeper coding standards before, would save me so much pain now.

Nono, tests are not run. Do you see them somewhere?

**Comment by jankal** [comment]
Nah I thought so. Didn't know, that it's possible to get Coverage without running the tests.

**Comment by jankal** [comment]
+1 for PHPStan!

**Comment by TomasVotruba** [comment]
The coverage is run once and uploaded here: https://github.com/ApiGen/ApiGen/pull/789/files#diff-354f30a63fb0907d4ad57269548329e3R24

This PR is done. 

I might do some more after this is merge. 

I'll focus on PHPStan and Coding Standard setup, so we have the best static analysis we can :)

**Comment by jankal** [comment]
@kukulich Is it okay that @TomasVotruba removed the LICENSE from the files heads?

Then this can be merged.

**Comment by TomasVotruba** [comment]
Thanks you so much for such feedback!

**Comment by jankal** [comment]
Thanks @TomasVotruba for so much work!

**Comment by kukulich** [comment]
Yes, one license should be enough for everyone :)

**Comment by jankal** [comment]
So I merge this now.

**Comment by jankal** [comment]
Done @TomasVotruba @kukulich

**Comment by TomasVotruba** [comment]
@kukulich Actually @ondrejmirtes inspired me to this :). I never really liked it, but everyone was using so I thought it was obligatory or something.

Much cleaner and easier to read the code without them :)

@jankal Thank you! :tada:

**Pull request merged**
