### PR TITLE
Drop Markdown

### PR DESCRIPTION
**Pull request by TomasVotruba**
### Why?

This brings various syntax problems and encourages people to actually use Markdown in PHP comments. I see this as a bad practice and source of great confusion what is formatted and how.

I consider this mixing of concerns. **Docblock should be used for information**, not for writing posts - blogs are for that. It would lighten this project a bit more.

I recall this brought so many issue with spaces, `<p>` left overs, lines vs. block and crippled code highlighting.

### Would resolve confusions and issues

- https://github.com/ApiGen/ApiGen/issues/772
- https://github.com/ApiGen/ApiGen/issues/426
- https://github.com/ApiGen/ApiGen/issues/671
- https://github.com/ApiGen/ApiGen/issues/647
- https://github.com/ApiGen/ApiGen/issues/671
- https://github.com/ApiGen/ApiGen/issues/634
- https://github.com/ApiGen/ApiGen/issues/543
- https://github.com/ApiGen/ApiGen/issues/426
- https://github.com/ApiGen/ApiGen/issues/541
- https://github.com/ApiGen/ApiGen/issues/597

### @example as specific and clear alternative

As already requested, annotation @example might do the trick just fine with much more predictable behavior
https://github.com/ApiGen/ApiGen/issues/718

### CODE REVIEW

**Comment by POPSuL** [comment]
Maybe the engine for rendering needs to be replaced? E.g. parsedown.
I'm against removing markdown support :(

**Comment by TomasVotruba** [comment]
We are in state of dying package with over 10 issues with this section. 
What value brings Markdown (or any -down) over missing PHP 7 reflection features?

**Comment by POPSuL** [comment]
Many issues caused by ugly markdown library which uses.
If we remove the markdown support - PHP7 support will not be improved, but the backwards compatibility will be broken.
I chosen ApiGen because it support markdown syntax for documenting, and I have many source code with markdown in phpDoc. I think I'm not the only one.

**Comment by TomasVotruba** [comment]
What is your use case?
What about event access for you to do anything you need?

**Comment by TomasVotruba** [comment]
Thing is about the maintenance overhead. The more there are feature, the less there is attention for them all.

**Comment by zonuexe** [comment]
Markdown is an important function, but I feel it is more buggy. I agree with this proposal.

**Comment by jankal** [comment]
Please get in touch with @kukulich if you need any repo write permission so you may fix the markdown engine. I personally also only consider this a real feature when no problems rising up in futur version will be related to it.

So when you do some work on it: please use a highly stable and supported rendering engine. As I see there's alreadfy been a little PR war about Markdown enignes. I don't want this again. Else we will drop it completly (this pull will tghen be accepted). 

Now on hold @POPSuL

**Comment by POPSuL** [comment]
Also @jadb and @deizel should be invited to this dispute.
IMHO - markdown is a killer feature for apigen. Nobody wants write HTML markup in own PHP sources (its ugly). Markdown have perfect readability in source code and it should be presented in apigen.
michelf/php-markdown - is not better library for md rendering, there are alternatives.
As @TomasVotruba says "we have many troubles with apigen, we don't have support PHP7, we have many issues about rendering (md rendering)". But how does md support related to PHP7 support? 
If we remove md support and close 10-20-30 issues, implementation for PHP7 support will not become easer.
I propose replace md-renderer with better library...

**Comment by TomasVotruba** [comment]
@POPSuL 

> If we remove md support and close 10-20-30 issues, implementation for PHP7 support will not become easer.

Actually it will, and much more. There is a thing called cognitive overload: brain is able to consume certain amount of data, then it become very inefficient. Same happens here. We have 15 issues around Markdown, but there is no support for PHP 5.5 feature. Why? Because Markdown took all the energy we've got. And new issues are and keep popping. 

Trust me, I speak from experience. I've taken over maintenance of this package ~3 years ago, when it was 2 years dead and last version broken. There we so many features, that none was able to find and fix one line in the template generator.

All features were as wanted as Texy/Markdown/Parsedown..., but it didn't work.

At this state. This project don't work, and people are preffering Sami and PhpDocumentor, because they do.

**I see this as sinking ship. We are too heavy and we don't want to let go of great food we have and we ignore this huge whole in the deck.**

Let's make a compromise. I suggest we drop this for now and when we're done with PHP 7.1 feature and they work, we can put this back. Knowing we are safe, ship is fixed and we can enjoy those awesome meals.

**Comment by jankal** [comment]
Yep @TomasVotruba I totally agree with this compromise.

@POPSuL is this fine for you?

**Comment by jankal** [comment]
I won't wait for weeks until @POPSuL replies.

If checks pass as expected, I will merge this very soon (today or tomorrow).

**Comment by TomasVotruba** [comment]
This has been merged to wrong branch. My fault.

I'll prepare new PR with event solution.

**Comment by jankal** [comment]
Oh. I just assumed you had control over your `drop-*` branches. After short discussion I'd approve everything cause it's not master.

I don't know your plans cause I myself would have made just one branch to combine it all so that branch can then be merged into master. Now you have like five branches.

**Comment by TomasVotruba** [comment]
I'm sorry for this mess. I'll be more careful now and since there is much less code know, it will be easier.

**Comment by TomasVotruba** [comment]
@POPSuL It is now possible to modify docs output via event. 
You can easily access it via `EventSubscriber` and modify it to meet your needs - Markdown, Parsedown, Texy or anything you need.

**Comment by jankal** [comment]
@TomasVotruba +1 for Events.

**Comment by POPSuL** [comment]
Thanks for events!

**Pull request merged**
