### PR TITLE
[BetterReflection] replacement - part 1

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref #817 

### Also includes

- #818  - split class generator to class, trait and interface
- exception generator dropped
- drop Theme and all related configuration overhead
    - use `themeDirectory` instead

### CODE REVIEW

**Comment by jankal** [comment]
+1

**Comment by jankal** [comment]
Added reviwers due to this being a critical change.

**Comment by TomasVotruba** [comment]
@jankal I'd wait until this is finished. It's WIP

**Comment by jankal** [comment]
Why the fuck am I not able to add me and @ek9 as reviewers?

**Comment by TomasVotruba** [comment]
@jankal There's lot of work now, so I've opened a new PR where I continue my work. This PR is finished. **Do not merge it**, I will do so when all following ones are.

Could I ask you for partial review?

**Pull request merged**
