### PR TITLE
[WIP] Drop package grouping, use namespace by default

### PR DESCRIPTION
**Pull request by TomasVotruba**
I've never seen project using ApiGen and packages.
From PHP 5.3+ times I consider this deprecated feature that has no added value for present code.

Related: https://github.com/ApiGen/ApiGen/issues/747

### CODE REVIEW

**Comment by jankal** [comment]
+1 This will probably make it in.

**Comment by POPSuL** [comment]
+1

**Comment by jankal** [comment]
One test is now FAILING. Will not merge until this has been resolved.

**Comment by TomasVotruba** [comment]
I will check it. Thank you guys for such positive feedback!

**Comment by TomasVotruba** [comment]
Replaced by #802

**Pull request closed without merging**
